### ISSUE TITLE
Geo Search demo - Change the marker on the map when you hover on the result page

### ISSUE THREAD

**Issue by JeanEdern** [algolia/examples#11]
A client asked me if it was possible to change the marker on the map when you hover on an item in the result page. like on http://www.beaune-tourisme.fr/se-loger/hotels#!/page/1
Though it's not really related to Algolia, it could be great to show that in the geo search demo.

**Comment by Haroenv** [comment]
A custom marker is possible, but it's based on the google marker options (code [here](https://github.com/algolia/demo-geo-search/blob/c3a5529cf6d8f4710102725f1d00b40c9a8b6671/app/js/app.js#L204-L209)). With the replacement of this in InstantSearch.js the demo is visible [here](https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=GeoSearch.with%20HTML%20marker%20%26%20InfoBox) ([code here](https://github.com/algolia/instantsearch.js/blob/0d90276af4ba40bc32a5da5ba9c6d5dca9eab9f0/dev/app/builtin/stories/geo-search.stories.js#L532-L579))
