### ISSUE TITLE
The example code in the doc isn't working

### ISSUE THREAD

**Issue by Maaark** [algolia/examples#17]
The example code in the doc isn't working - empty items are appended.

**Comment by dustincoates** [comment]
@Maaark Which example are you looking at?

**Comment by Maaark** [comment]
@dustincoates https://www.algolia.com/doc/search/infinite-scroll#browsing-records
It seems to go wrong with the template rendering part, the hits aren't parsed or so.

**Comment by dustincoates** [comment]
@Maaark Thanks for pointing that out. There's a typo, it appears: `var results` should be `var result`. We'll get it fixed.

No need to use Hogan--the widgets are completely agnostic to the technology and in fact the default instantsearch.js widgets are with React.

**Comment by Maaark** [comment]
@dustincoates Thanks :)
About the template part, I meant to ask if I could use the templating functions in my own custom widget? So I wouldn't need to include Mustache/Hogan/React myself? Building a custom pagination widget that appends the next page results to the hits container after clicking a button and I'm a bit lost since I'm not familiar with React or any other javascript framework besides jQuery :P

**Comment by dustincoates** [comment]
@Maaark If I understand correctly, you can render the templates without needing a templating library. You'll need to build the elements and add to the DOM.

**Comment by Maaark** [comment]
@dustincoates Nvm, already solved.
