### ISSUE TITLE
adding infinite search following tutorial

### ISSUE THREAD

**Issue by talha-malik** [algolia/examples#18]
Hi,
I am trying to add infinite scroll with algolia search. I followed [this tutorial](https://www.algolia.com/doc/guides/search/infinite-scrolll) but I am getting an error when algolia request for next items is sent. I have shared my code [at stackoverflow](http://stackoverflow.com/questions/38462479/algolia-seach-adding-infinite-scrolll) I can see i have messed up in the given code but I a unable to fix it. Please guide.

**Comment by dustincoates** [comment]
@talha-malik I'm looking into this and will get back to you.

**Comment by talha-malik** [comment]
Thanks a lot

**Comment by talha-malik** [comment]
Hello @dustincoates 
were you able to look into above mentioned issue. 
Thanks

**Comment by dustincoates** [comment]
@talha-malik I have it on my to do list to take care of today. I'll be sure to tag you when I get to it.

**Comment by talha-malik** [comment]
right. Thanks for your time. Really appreciate it.

**Comment by dustincoates** [comment]
@talha-malik Thank you for bringing this up. It's been on my to-do list to take another look at this guide and this was a good opportunity. I'm sorry you ran into some issues with it.

The problem was in the `appendSearchResults` method. At one point it said:
```args.results.pageNo = page + 1;```

Now it says:
```res.pageNo = page + 1;```

Hope this helps!
