### ISSUE TITLE
unable to test examples/infinite-scroll

### ISSUE THREAD

**Issue by chriscalip** [algolia/examples#19]
Steps to replicate:
`
cd infinite-scroll
npm install
npm start
`
when to http://localhost:8080/
![bugreport-infinite-scoll](https://cloud.githubusercontent.com/assets/479454/17037147/199b85c0-4f55-11e6-88b7-94921eed1c4a.png)

**Comment by dustincoates** [comment]
@chriscalip Thanks for bringing this up. Do you have the `style.css` present in your project?

**Comment by chriscalip** [comment]
@dustincoates I did not make any updates at the directory other than executing those commands.. i saw that its in src/css/style.css

**Comment by chriscalip** [comment]
Steps to reproduce:
`
git clone https://github.com/algolia/examples.git examples
cd examples/infinite-scroll/
npm install
npm start
`
I then looked http://localhost:8080/

**Comment by dustincoates** [comment]
@chriscalip Thanks for bumping this back up. I'll give it a try today and get back to you.

**Comment by dustincoates** [comment]
@chriscalip I was unable to reproduce. I'm going to bring in a colleague with a Linux machine. In the interim if you're just looking to try out the example, the `build` directory is fully built—we primarily use the build step for organization.

**Comment by chriscalip** [comment]
@dustincoates 
Trying to move this forward.

Attached are screenshots of cloning the repo and rendering examples/infinite-scroll/build/index.html

![examples-cloned](https://cloud.githubusercontent.com/assets/479454/17566397/caf9b9da-5f00-11e6-81cb-6f8ce694dfe8.png)
![examples-rendered](https://cloud.githubusercontent.com/assets/479454/17566396/caf12248-5f00-11e6-957d-240af2071038.png)

**Comment by dustincoates** [comment]
Thanks for these screenshots @chriscalip. It is useful to see the different errors  in the build itself. Working to get a colleague in on a Linux machine. I'll keep you up to date!

**Comment by dustincoates** [comment]
@chriscalip Can you let me know if this branch in `build` works for you? It looks like the result of a bad build.

https://github.com/algolia/examples/tree/fix-infinite-scroll-build

**Comment by chriscalip** [comment]
More data, screenshots from a windows machine, waterfox and chrome browsers.

![examples-windows-chrome](https://cloud.githubusercontent.com/assets/479454/17567784/6ac38f54-5f06-11e6-8408-c8f28a611745.png)
![examples-windows-waterfox](https://cloud.githubusercontent.com/assets/479454/17567783/6ac276c8-5f06-11e6-987d-4f360fc2c554.png)

**Comment by chriscalip** [comment]
Indeed! that branch has the fixed!
![fix-examples-windows-chrome](https://cloud.githubusercontent.com/assets/479454/17567936/092a4cfa-5f07-11e6-9f51-8ae25c7b72e0.png)
![fix-examples-windows-waterfox](https://cloud.githubusercontent.com/assets/479454/17567935/09299f80-5f07-11e6-9cd8-6488e9ca17ac.png)

**Comment by dustincoates** [comment]
@chriscalip Huzzah! Thanks for your patience--I'll merge it in.
