### ISSUE TITLE
Linting is not enforced

### ISSUE THREAD

**Issue by pixelastic** [algolia/examples#23]
We have Travis to force us to run `npm run lint` on every commit, but the build have been failing for the past 9 months and we are not doing anything :cry: 

FYI, here is the list of linting errors found by our current config:

```
/home/tim/local/www/algolia/demos/examples/infinite-scroll/build/js/app.js
  0:0  error  Parsing error: Maximum call stack size exceeded

/home/tim/local/www/algolia/demos/examples/infinite-scroll/webpack.config.js
   1:1   error  Do not mix core, module, file and computed requires     no-mixed-requires
   1:1   error  Split 'var' declarations into multiple statements       one-var
   2:5   error  Expected indentation of 2 space characters but found 4  indent
   3:5   error  Expected indentation of 2 space characters but found 4  indent
  22:13  error  Missing space before value for key "loaders"            key-spacing
  28:16  error  Extra space before value for key "test"                 key-spacing
  34:2   error  Missing semicolon                                       semi

/home/tim/local/www/algolia/demos/examples/instant-search/jquery/js/app.js
  211:11  error  Unquoted reserved word `class` used as key  quote-props
  223:15  error  Unquoted reserved word `class` used as key  quote-props
  238:15  error  Unquoted reserved word `class` used as key  quote-props

/home/tim/local/www/algolia/demos/examples/keywords-suggestion/js/app.js
  1:36  error  "algoliasearchHelper" is defined but never used  no-unused-vars

```

cc @vvo @bobylito @mthuret Is the linting config up to date with what you're currently suggesting in the other projects?

**Comment by vvo** [comment]
What we use right now in the JavaScript team: https://github.com/algolia/eslint-config-algolia

It enforces ES6 semantics like arrow functions where relevant. A lot of those issues are fixable automatically by eslint (eslint --fix). I don't know if this style guide is relevant for the examples repo.

Ultimately having a similar style guide on all our JavaScript projects would be something interesting from my POV, to ease the reading and collaboration.

**Comment by pixelastic** [comment]
Yep, I think it makes sense that our examples also follow what we consider
as best practices.
