### ISSUE TITLE
Missing app.js on example website

### ISSUE THREAD

**Issue by bakerstreetsystems** [algolia/examples#35]
I'm working through the instant search tutorial and using the demo page found here:

https://demo.algolia.com/examples/instant-search/jquery/

Within the past few minutes, the page has stopped working, and I think it's because the app.js file is no longer being loaded. The HTML loads just fine, but the results don't show up, and I think it's because Algolia search is never initialized from the app.js file. When you go to https://demo.algolia.com/examples/instant-search/jquery/js/app.js, you just get a 404 error.

Just thought someone should know...

**Comment by Haroenv** [comment]
Looks like it works for me, but I saw that there was an issue earlier this day on our demo website, maybe related?

**Comment by bakerstreetsystems** [comment]
I connected to one of my VPNs and it works now for me... maybe one of your load-balanced servers was out of sync of something? I was trying to access the page from American Fork, Utah, btw.

**Comment by Haroenv** [comment]
I seem to have the issue now.

**Comment by vvo** [comment]
Works for me from here.

**Comment by Haroenv** [comment]
Please open a new issue with relevant info if this happens again :)
