### ISSUE TITLE
THe package react-instantsearch does not work

### ISSUE THREAD

**Issue by foufrix** [algolia/examples#42]
Hello,

I tried to test the example version of react-instantsearch, and it's look like it's not working and have dependencies issues (i think ?)

As i use principaly angular and wanted to see how instantsearch work with react and if it's valuable for me to switch all my project from Angular 4 to react because Search will be a big part of my website, i would like to have a working demo if possible under react please ? I'm discovering react and a working demo would help me a lot.

Thanks in advance.

**Comment by Haroenv** [comment]
Can you explain which demo has an error? All the examples for react-instantsearch are also available in its repository: https://github.com/algolia/react-instantsearch/tree/master/packages/react-instantsearch/examples. 

Feel free to reopen if you have other troubles, or open an issue on the react-instantsearch repository 

Have a good day ❤️

**Comment by foufrix** [comment]
Hello,

Yes with pleasure,

I cloned this github package, and followed all the insctructions, and it's not starting, apparently somme package are deprecated ?

**Comment by Haroenv** [comment]
You were right, the demo in this repository had outdated dependencies. If you check out to my branch (`fix/react-instantsearch-demo`), or master after #43 has been merged you'll find a working version. Completely updated examples are also available at https://github.com/algolia/react-instantsearch/tree/master/packages/react-instantsearch/examples

**Comment by foufrix** [comment]
Thanks works perfectly
