### ISSUE TITLE
Infinite scroll not working

### ISSUE THREAD

**Issue by abou-emish** [algolia/examples#46]
On my mac, I opened the URL [demo-infinite-scroll](https://community.algolia.com/demo-infinite-scroll/) but it's not scrolling. Am I missing something? :)

**Comment by Haroenv** [comment]
It seems to work for me, what kind of setup do you have exactly? Are there any errors in the console maybe?

**Comment by abou-emish** [comment]
It's working in Safari, but not Google Chrome, the console is clean

IOS: 10.13.6

Chrome: Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by abou-emish** [comment]
Thanks, that example is working, when you have time you can update the example URL here ;)

**Comment by Haroenv** [comment]
That example I wrote is actually part of another guide, but yes, I'll change the links here when that one is published
