### ISSUE TITLE
Use a single coding style/eslint

### ISSUE THREAD

**Issue by vvo** [algolia/examples#5]
Could the examples/ code use the https://github.com/algolia/eslint-config-algolia rules? So that we all align on almost the same coding style accross our JavaScript projects.

Let me know

**Comment by dustincoates** [comment]
@vvo Yes! :heart: :heart_eyes: :heart_eyes_cat:

**Comment by olance** [comment]
:)

Funny that was a discussion within the CSE team @vvo!
I guess it makes sense that we adopt the same coding styles as much as possible :)

**Comment by proudlygeek** [comment]
And same tooling, I would add :wink:

**Comment by olance** [comment]
Well that would depend on the tooling @proudlygeek: at least for demos, we don't want too much friction so that they can be done as quickly as possible. So there's probably a tradeoff to be found there.
But it would make sense for public examples :)
